### ISSUE TITLE
Medoid compositing method always running out of memory?

### ISSUE THREAD

**Issue by orbitfold** [dugalh/geedim#11]
I'm interested in this approach but whenever I try it it always runs out of memory (even though other compositing methods work fine with the same settings)

**Comment by dugalh** [comment]
If the image computation is running over the user memory limit on download, you can reduce the `max_tile_size` parameter.  I suggest trying `max_tile_size=8` (MB).  The command line docs are [here](https://geedim.readthedocs.io/en/latest/cli.html#cmdoption-geedim-download-mts) and the API docs [here](https://geedim.readthedocs.io/en/latest/_generated/geedim.mask.MaskedImage.download.html).

**Comment by orbitfold** [comment]
Hi Dugal, 8 is what I have it set to after experimenting for a value that stops throwing those memory errors 99% of the time, I think something more is going on here. Does this method work for you?

**Comment by dugalh** [comment]
Hello, I have seen a "user memory limit exceeded" error when downloading a large Sentinel-2 medoid composite.  When I decreased `max_tile_size`, it downloaded ok.   

Earth engine has a size limit (32 MB) on [download](https://developers.google.com/earth-engine/apidocs/ee-image-getdownloadurl) requests.  `geedim` calculates the download tile sizes so that this is not exceeded.   Earth engine also has a [limit on user memory](https://developers.google.com/earth-engine/guides/usage#per-request_memory_footprint) for image computations.  This limit can still be exceeded when downloading computed images (e.g. medoid composites) with `geedim`.  Unfortunately there is no way for `geedim` to know the memory requirements of a computation in advance.  So it is up to the user to adjust `max_tile_size` if they run into memory issues.  

Alternatively, exporting is not subject to the user memory limit, so a user could export their computed image to an [asset](https://developers.google.com/earth-engine/apidocs/export-image-toasset), and then download the asset image with `geedim`.

If you think there is something else going wrong, please provide code to recreate the problem case.

**Comment by orbitfold** [comment]
I will try with even smaller tile sizes when I get a chance (next week)

**Comment by dugalh** [comment]
See the [related documentation section](https://geedim.readthedocs.io/en/latest/api.html#computed-images-and-user-memory) in the latest release.

**Comment by orbitfold** [comment]
Well, for me it doesn't work even if I reduce max_tile_size to 0.1

**Comment by orbitfold** [comment]
Here is the GeoJSON I've used.

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              -0.3689373648039975,
              5.785841065493003
            ],
            [
              -0.3689373648039975,
              5.364440103464588
            ],
            [
              0.05576223573189054,
              5.364440103464588
            ],
            [
              0.05576223573189054,
              5.785841065493003
            ],
            [
              -0.3689373648039975,
              5.785841065493003
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}
```

**Comment by orbitfold** [comment]
Btw, if it helps, the error seems to happen before it starts downloading

**Comment by dugalh** [comment]
OK.  Can you tell me the value of `collection`?

**Comment by orbitfold** [comment]
'COPERNICUS/S2_SR_HARMONIZED'

**Comment by dugalh** [comment]
The latest [v1.7.0](https://github.com/dugalh/geedim/releases/tag/v1.7.0) release contains some improvements and an [example](https://geedim.readthedocs.io/en/latest/examples/s2_composite.html) related to this.
